baseURL = "https://akherlan.github.io/"
languageCode = "id-id"
theme = "etch-notation"
title = "Notebook"
paginate = 10
enableInlineShortcodes = true
enableEmoji = true
# use class names instead of directly inserting color codes
pygmentsUseClasses = true
# enable GitHub style code snippets
pygmentsCodeFences = true
defaultContentLanguage = 'id'

[params]
	description = "Catatan kecil Andi."
	copyright = "Powered by Hugo and Github Page."
	dark = "off"
	highlight = true

[menu]
	[[menu.main]]
		identifier = "about"
		name = "about"
		title = "about"
		url = "/about/"
		weight = 10

	[[menu.main]]
		identifier = "now"
		name = "now"
		title = "now"
		url = "/now/"
		weight = 11

	[[menu.main]]
		identifier = "read"
		name = "read"
		title = "read"
		url = "/read/"
		weight = 12

	[[menu.main]]
		identifier = "rss"
		name = "rss"
		title = "rss"
		url = "/index.xml"
		weight = 13

[permalinks]
	posts = "/:title/"

[markup.goldmark.renderer]
	# Allows HTML in Markdown
	unsafe = true

