baseURL = "https://akherlan.github.io/"
languageCode = "en-us"
theme = "etch"
title = "Notebook"
pygmentsUseClasses = true  # use class names instead of directly inserting color codes
pygmentsCodeFences = true  # enable GitHub style code snippets

[params]
	description = "Catatan kecil Andi."
	copyright = "Empowered with Hugo and Github Page."
	dark = "auto"
	highlight = true

[menu]
	[[menu.main]]
		identifier = "about"
		name = "about"
		title = "about"
		url = "/about/"
		weight = 20

[permalinks]
	posts = "/:title/"

[markup.goldmark.renderer]
	# Allows HTML in Markdown
	unsafe = true
